receivers:
  otlp:
    protocols:
      grpc:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_http:
  zipkin:

exporters:
  otlp:
    #push_config:
    endpoint: "otel-collector:4317"
    #basic_auth:
     # username: dockeradmin
      #password: dockeradmin@1234      
              #    endpoint: "13.67.226.140:4317"
    insecure: true
  logging:
    loglevel: debug

processors:
  batch:
          
extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extentions: [health_check, pprof, zpages]     
  pipelines:
    traces:
      receivers: [otlp, opencensus, zipkin, jaeger]
      processors: [batch]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [otlp, logging]
